### ISSUE TITLE
Unknown Axios Error

### ISSUE THREAD

**Issue by Jacobsolawetz** [roboflow-ai/inference-server#2]
![image](https://user-images.githubusercontent.com/8428198/152204806-3afd1b10-ab18-47ff-a5a9-87716b2b29f2.png)

User was attempting to replicate commands identical to Charles and I, which were successful on two respective Jetsons

**Comment by yeldarby** [comment]
Sounds like it’s likely to be a network/firewall block of our API or some of the google services. Can they access Roboflow on a web browser on the jetson?

**Comment by Jacobsolawetz** [comment]
they can `curl https://api.roboflow.com` successfully on their jetson

**Comment by Jacobsolawetz** [comment]
Maybe on the GCP download?

**Comment by yeldarby** [comment]
Closing this issue as stale.
