### ISSUE TITLE
Want to deploy a custom model using roboflow (Without training on roboflow)

### ISSUE THREAD

**Issue by Kapil-23** [roboflow-ai/inference-server#6]
Scenario : 
Picking up a pretrained model from open source project say tensorflow. (Note : I have not trained the model using roboflow)
Further need to deploy on Jetson Xavier using Roboflow Inference server docker.
Can i achieve this scenario ?

**Comment by yeldarby** [comment]
Cool idea, but not something we are able to support at this time.

Our machine learning team has spent a ton of time hand-tuning our models to run reliably on edge devices and it’s not really generalizable.
